name: Rust
permissions:
  contents: read
on:
  push:
    paths:
      - "daemon"
      - ".github/workflows/rust.yml"

defaults:
  run:
    working-directory: daemon

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # v1.94.1
        with:
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check
  clippy:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # v1.94.1
        with:
          toolchain: stable
          components: clippy

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run: cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
        env:
          CARGO_TERM_VERBOSE: false

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4.38.2
        with:
          sarif_file: daemon/rust-clippy-results.sarif
          wait-for-processing: true
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Pre-test
        run: |
          sudo apt update && sudo apt install libudev-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # v1.94.1
        with:
          toolchain: stable

      - name: Cache Rust dependencies and build artifacts
        if: inputs.test-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/git/checkouts/
            daemon/target/
          key: ${{ runner.os }}-test-cargo-${{ hashFiles('daemon/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-cargo-

      - name: Fetch
        run: cargo fetch --locked

      - name: Build
        run: cargo build --frozen

      - name: Run tests
        run: cargo test
